services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      STRING_SESSION: $STRING_SESSION
      DATABASE_URL: $DATABASE_URL
      BOTLOGS: $BOTLOGS
      HANDLER: $HANDLER
      NO_HANDLER: $NO_HANDLER
      TZ: $TZ
      LANG_CODE: $LANG_CODE
    restart: unless-stopped
