services:
  getter:
    build:
      context: .
      dockerfile: Dockerfile.lite
    image: getter:latest
    restart: on-failure
    volumes:
      - ./:/app
    env_file:
      - config.env
    network_mode: bridge
